#
# application.yml — главный конфигурационный файл Spring Boot.

spring:
  datasource:
    url: jdbc:postgresql://db:5432/card_db
    username: ${DB_USER:card}
    password: ${DB_PASS:card}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
liquibase:
  change-log: classpath:db/migration/db.changelog-master.yaml

security:
  jwt:
    secret: ${JWT_SECRET:secret} #TODO
    expiration-ms: 3600000
    token-prefix: "Bearer "
    header-string: "Authorization"

app:
  crypto:
    key: ${APP_CRYPTO_KEY:base64encoded32bytes} # TODO

logging:
  level:
    root: INFO
    com.example.cardservice: DEBUG
  file:
    name: logs/card-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

services:
  db:
    image: postgres:15